// Total snippets: 13
// -----------------------------------------
// Snippet #0 platforms ffffffff:
SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #1 platforms ffffffdf:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP
FOG_EXP FOG_EXP2 FOG_LINEAR
DIRECTIONAL DIRLIGHTMAP_COMBINED DIRLIGHTMAP_OFF DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON LIGHTMAP_OFF LIGHTMAP_ON SHADOWS_NATIVE SHADOWS_OFF SHADOWS_SCREEN VERTEXLIGHT_ON

12 keyword variants used in scene:

DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF VERTEXLIGHT_ON _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN VERTEXLIGHT_ON _NORMALMAP


// -----------------------------------------
// Snippet #2 platforms ffffffff:
FOG_EXP FOG_EXP2 FOG_LINEAR POINT SPOT

3 keyword variants used in scene:

<no keywords defined>
POINT
SPOT


// -----------------------------------------
// Snippet #3 platforms ffffffdf:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP
FOG_EXP FOG_EXP2 FOG_LINEAR
DIRECTIONAL DIRECTIONAL_COOKIE POINT POINT_COOKIE SHADOWS_CUBE SHADOWS_DEPTH SHADOWS_NATIVE SHADOWS_NONATIVE SHADOWS_OFF SHADOWS_SCREEN SHADOWS_SOFT SPOT

34 keyword variants used in scene:

POINT SHADOWS_OFF
DIRECTIONAL SHADOWS_OFF
SHADOWS_OFF SPOT
POINT_COOKIE SHADOWS_OFF
DIRECTIONAL_COOKIE SHADOWS_OFF
SHADOWS_DEPTH SHADOWS_NONATIVE SPOT
SHADOWS_DEPTH SHADOWS_NATIVE SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE
SHADOWS_DEPTH SHADOWS_NONATIVE SHADOWS_SOFT SPOT
SHADOWS_DEPTH SHADOWS_NATIVE SHADOWS_SOFT SPOT
POINT SHADOWS_CUBE SHADOWS_SOFT
POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT
DIRECTIONAL SHADOWS_NATIVE SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_NATIVE SHADOWS_SCREEN
POINT SHADOWS_OFF _NORMALMAP
DIRECTIONAL SHADOWS_OFF _NORMALMAP
SHADOWS_OFF SPOT _NORMALMAP
POINT_COOKIE SHADOWS_OFF _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_OFF _NORMALMAP
SHADOWS_DEPTH SHADOWS_NONATIVE SPOT _NORMALMAP
SHADOWS_DEPTH SHADOWS_NATIVE SPOT _NORMALMAP
DIRECTIONAL SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_SCREEN _NORMALMAP
POINT SHADOWS_CUBE _NORMALMAP
POINT_COOKIE SHADOWS_CUBE _NORMALMAP
SHADOWS_DEPTH SHADOWS_NONATIVE SHADOWS_SOFT SPOT _NORMALMAP
SHADOWS_DEPTH SHADOWS_NATIVE SHADOWS_SOFT SPOT _NORMALMAP
POINT SHADOWS_CUBE SHADOWS_SOFT _NORMALMAP
POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT _NORMALMAP
DIRECTIONAL SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP


// -----------------------------------------
// Snippet #4 platforms ffffffdf:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON
SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #5 platforms ffffffff:
FOG_EXP FOG_EXP2 FOG_LINEAR

Just one shader variant.


// -----------------------------------------
// Snippet #6 platforms ffffdbdf:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP
DIRLIGHTMAP_COMBINED DIRLIGHTMAP_OFF DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON LIGHTMAP_OFF LIGHTMAP_ON UNITY_HDR_ON

12 keyword variants used in scene:

DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF _NORMALMAP
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF _NORMALMAP
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF _NORMALMAP
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON _NORMALMAP
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON _NORMALMAP
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF UNITY_HDR_ON _NORMALMAP


// -----------------------------------------
// Snippet #7 platforms ffffffff:
FOG_EXP FOG_EXP2 FOG_LINEAR

Just one shader variant.


// -----------------------------------------
// Snippet #8 platforms ffffffff:
_DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP

Just one shader variant.


// -----------------------------------------
// Snippet #9 platforms ffffffff:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _NORMALMAP
FOG_EXP FOG_EXP2 FOG_LINEAR
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON LIGHTMAP_OFF LIGHTMAP_ON SHADOWS_NATIVE SHADOWS_OFF SHADOWS_SCREEN VERTEXLIGHT_ON

12 keyword variants used in scene:

DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_OFF VERTEXLIGHT_ON _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_NATIVE SHADOWS_SCREEN VERTEXLIGHT_ON _NORMALMAP


// -----------------------------------------
// Snippet #10 platforms ffffffff:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP
FOG_EXP FOG_EXP2 FOG_LINEAR
DIRECTIONAL DIRECTIONAL_COOKIE POINT POINT_COOKIE SHADOWS_CUBE SHADOWS_DEPTH SHADOWS_NATIVE SHADOWS_NONATIVE SHADOWS_OFF SHADOWS_SCREEN SPOT

26 keyword variants used in scene:

POINT SHADOWS_OFF
DIRECTIONAL SHADOWS_OFF
SHADOWS_OFF SPOT
POINT_COOKIE SHADOWS_OFF
DIRECTIONAL_COOKIE SHADOWS_OFF
SHADOWS_DEPTH SHADOWS_NONATIVE SPOT
SHADOWS_DEPTH SHADOWS_NATIVE SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE
DIRECTIONAL SHADOWS_NATIVE SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_NATIVE SHADOWS_SCREEN
POINT SHADOWS_OFF _NORMALMAP
DIRECTIONAL SHADOWS_OFF _NORMALMAP
SHADOWS_OFF SPOT _NORMALMAP
POINT_COOKIE SHADOWS_OFF _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_OFF _NORMALMAP
SHADOWS_DEPTH SHADOWS_NONATIVE SPOT _NORMALMAP
SHADOWS_DEPTH SHADOWS_NATIVE SPOT _NORMALMAP
DIRECTIONAL SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_SCREEN _NORMALMAP
POINT SHADOWS_CUBE _NORMALMAP
POINT_COOKIE SHADOWS_CUBE _NORMALMAP
DIRECTIONAL SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP
DIRECTIONAL_COOKIE SHADOWS_NATIVE SHADOWS_SCREEN _NORMALMAP


// -----------------------------------------
// Snippet #11 platforms ffffffff:
_ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON
SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #12 platforms ffffffff:
_DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP

Just one shader variant.


